// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatRemote.proto

package srcs.chat;

public interface ChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:srcs.chat.ChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sender = 1;</code>
   */
  java.lang.String getSender();
  /**
   * <code>string sender = 1;</code>
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <code>string content = 2;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
