// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatRemote.proto

package srcs.chat;

public final class ChatRemote {
  private ChatRemote() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_srcs_chat_SubscribeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_srcs_chat_SubscribeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_srcs_chat_SubscribeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_srcs_chat_SubscribeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_srcs_chat_UnsubscribeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_srcs_chat_UnsubscribeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_srcs_chat_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_srcs_chat_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_srcs_chat_SendRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_srcs_chat_SendRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_srcs_chat_SendResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_srcs_chat_SendResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_srcs_chat_ListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_srcs_chat_ListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_srcs_chat_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_srcs_chat_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020chatRemote.proto\022\tsrcs.chat\"A\n\020Subscri" +
      "beRequest\022\016\n\006pseudo\030\001 \001(\t\022\017\n\007ip_host\030\002 \001" +
      "(\t\022\014\n\004port\030\003 \001(\005\"#\n\021SubscribeResponse\022\016\n" +
      "\006status\030\001 \001(\010\"$\n\022UnsubscribeRequest\022\016\n\006p" +
      "seudo\030\001 \001(\t\"\007\n\005Empty\".\n\013SendRequest\022\016\n\006p" +
      "seudo\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\"\037\n\014SendResp" +
      "onse\022\017\n\007nbUsers\030\001 \001(\005\"\037\n\014ListResponse\022\017\n" +
      "\007pseudos\030\001 \003(\t\".\n\013ChatMessage\022\016\n\006sender\030" +
      "\001 \001(\t\022\017\n\007content\030\002 \001(\t2\214\002\n\013ChatService\022F" +
      "\n\tsubscribe\022\033.srcs.chat.SubscribeRequest" +
      "\032\034.srcs.chat.SubscribeResponse\022>\n\013unsubs" +
      "cribe\022\035.srcs.chat.UnsubscribeRequest\032\020.s" +
      "rcs.chat.Empty\022>\n\013sendMessage\022\026.srcs.cha" +
      "t.SendRequest\032\027.srcs.chat.SendResponse\0225" +
      "\n\010listChat\022\020.srcs.chat.Empty\032\027.srcs.chat" +
      ".ListResponse2H\n\016MessageService\0226\n\nnewMe" +
      "ssage\022\026.srcs.chat.ChatMessage\032\020.srcs.cha" +
      "t.EmptyB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_srcs_chat_SubscribeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_srcs_chat_SubscribeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_srcs_chat_SubscribeRequest_descriptor,
        new java.lang.String[] { "Pseudo", "IpHost", "Port", });
    internal_static_srcs_chat_SubscribeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_srcs_chat_SubscribeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_srcs_chat_SubscribeResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_srcs_chat_UnsubscribeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_srcs_chat_UnsubscribeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_srcs_chat_UnsubscribeRequest_descriptor,
        new java.lang.String[] { "Pseudo", });
    internal_static_srcs_chat_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_srcs_chat_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_srcs_chat_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_srcs_chat_SendRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_srcs_chat_SendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_srcs_chat_SendRequest_descriptor,
        new java.lang.String[] { "Pseudo", "Message", });
    internal_static_srcs_chat_SendResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_srcs_chat_SendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_srcs_chat_SendResponse_descriptor,
        new java.lang.String[] { "NbUsers", });
    internal_static_srcs_chat_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_srcs_chat_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_srcs_chat_ListResponse_descriptor,
        new java.lang.String[] { "Pseudos", });
    internal_static_srcs_chat_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_srcs_chat_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_srcs_chat_ChatMessage_descriptor,
        new java.lang.String[] { "Sender", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
