// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatRemote.proto

package srcs.chat;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:srcs.chat.Empty)
    com.google.protobuf.MessageOrBuilder {
}
