// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatRemote.proto

package srcs.chat;

public interface ListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:srcs.chat.ListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string pseudos = 1;</code>
   */
  java.util.List<java.lang.String>
      getPseudosList();
  /**
   * <code>repeated string pseudos = 1;</code>
   */
  int getPseudosCount();
  /**
   * <code>repeated string pseudos = 1;</code>
   */
  java.lang.String getPseudos(int index);
  /**
   * <code>repeated string pseudos = 1;</code>
   */
  com.google.protobuf.ByteString
      getPseudosBytes(int index);
}
