// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatRemote.proto

package srcs.chat;

public interface SendResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:srcs.chat.SendResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 nbUsers = 1;</code>
   */
  int getNbUsers();
}
