// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatRemote.proto

package srcs.chat;

public interface SubscribeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:srcs.chat.SubscribeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   */
  boolean getStatus();
}
