// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatRemote.proto

package srcs.chat;

public interface SubscribeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:srcs.chat.SubscribeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pseudo = 1;</code>
   */
  java.lang.String getPseudo();
  /**
   * <code>string pseudo = 1;</code>
   */
  com.google.protobuf.ByteString
      getPseudoBytes();

  /**
   * <code>string ip_host = 2;</code>
   */
  java.lang.String getIpHost();
  /**
   * <code>string ip_host = 2;</code>
   */
  com.google.protobuf.ByteString
      getIpHostBytes();

  /**
   * <code>int32 port = 3;</code>
   */
  int getPort();
}
