// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatRemote.proto

package srcs.chat;

public interface UnsubscribeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:srcs.chat.UnsubscribeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pseudo = 1;</code>
   */
  java.lang.String getPseudo();
  /**
   * <code>string pseudo = 1;</code>
   */
  com.google.protobuf.ByteString
      getPseudoBytes();
}
