// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package srcs.inventory;

public final class Inventory {
  private Inventory() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_srcs_inventory_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_srcs_inventory_Product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_srcs_inventory_StockChange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_srcs_inventory_StockChange_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017inventory.proto\022\016srcs.inventory\032\036googl" +
      "e/protobuf/wrappers.proto\032\033google/protob" +
      "uf/empty.proto\"B\n\007Product\022\n\n\002id\030\001 \001(\t\022\013\n" +
      "\003nom\030\002 \001(\t\022\020\n\010quantite\030\003 \001(\005\022\014\n\004prix\030\004 \001" +
      "(\001\")\n\013StockChange\022\n\n\002id\030\001 \001(\t\022\016\n\006change\030" +
      "\002 \001(\0052\336\001\n\020InventoryService\022C\n\ngetProduct" +
      "\022\034.google.protobuf.StringValue\032\027.srcs.in" +
      "ventory.Product\022@\n\013listProduct\022\026.google." +
      "protobuf.Empty\032\027.srcs.inventory.Product0" +
      "\001\022C\n\013updateStock\022\033.srcs.inventory.StockC" +
      "hange\032\027.srcs.inventory.ProductB\002P\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_srcs_inventory_Product_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_srcs_inventory_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_srcs_inventory_Product_descriptor,
        new java.lang.String[] { "Id", "Nom", "Quantite", "Prix", });
    internal_static_srcs_inventory_StockChange_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_srcs_inventory_StockChange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_srcs_inventory_StockChange_descriptor,
        new java.lang.String[] { "Id", "Change", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
