// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package srcs.inventory;

public interface ProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:srcs.inventory.Product)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string nom = 2;</code>
   */
  java.lang.String getNom();
  /**
   * <code>string nom = 2;</code>
   */
  com.google.protobuf.ByteString
      getNomBytes();

  /**
   * <code>int32 quantite = 3;</code>
   */
  int getQuantite();

  /**
   * <code>double prix = 4;</code>
   */
  double getPrix();
}
