// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mapStringRem.proto

package srcs.map;

public interface EntryStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:srcs.map.EntryString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
