spring.application.name=webapp

server.port=9001

logging.level.root=error
logging.level.com.openclassroom=info
logging.level.org.springframework.boot.autoconfigure.h2=info
logging.level.org.springframework.boot.web.embedded.tomcat=info

# Custom
com.openclassroom.webapp.api-url=http://localhost:9000
